# Generated by Django 2.2.7 on 2019-11-25 03:19

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
from django.utils.timezone import utc


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='BugUser',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('password', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Ticket',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('time_created', models.DateTimeField(verbose_name=datetime.datetime(2019, 11, 25, 3, 19, 45, 869277, tzinfo=utc))),
                ('description', models.CharField(max_length=500)),
                ('submitters_name', models.CharField(max_length=100)),
                ('status', models.CharField(max_length=50)),
                ('completed_dev', models.CharField(max_length=100)),
                ('assigned_dev', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bugs_tracker.BugUser')),
            ],
        ),
        migrations.AddField(
            model_name='buguser',
            name='tickets',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bugs_tracker.Ticket'),
        ),
        migrations.AddField(
            model_name='buguser',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
