# Generated by Django 2.2.7 on 2019-11-25 15:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('bugs_tracker', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='buguser',
            name='tickets',
            field=models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to='bugs_tracker.Ticket'),
        ),
        migrations.AlterField(
            model_name='ticket',
            name='time_created',
            field=models.DateTimeField(),
        ),
    ]
