# Generated by Django 2.2.7 on 2019-11-25 16:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bugs_tracker', '0003_auto_20191125_1555'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='buguser',
            name='password',
        ),
    ]
