# Generated by Django 2.2.7 on 2019-11-26 16:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('bugs_tracker', '0005_auto_20191126_1610'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ticket',
            name='assigned_dev',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='bugs_tracker.BugUser'),
        ),
        migrations.AlterField(
            model_name='ticket',
            name='completed_dev',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='ticket_completed_dev', to='bugs_tracker.BugUser'),
        ),
    ]
