# Generated by Django 2.2.7 on 2019-11-26 16:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('bugs_tracker', '0006_auto_20191126_1613'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ticket',
            name='submitters_name',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ticket_submitters_name', to='bugs_tracker.BugUser'),
        ),
    ]
