# Generated by Django 2.2.7 on 2019-11-27 07:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bugs_tracker', '0007_auto_20191126_1615'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='buguser',
            name='tickets',
        ),
        migrations.AddField(
            model_name='buguser',
            name='tickets',
            field=models.ManyToManyField(blank=True, null=True, to='bugs_tracker.Ticket'),
        ),
    ]
