# Generated by Django 2.2.7 on 2019-11-28 17:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bugs_tracker', '0009_auto_20191127_0705'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ticket',
            name='status',
            field=models.IntegerField(),
        ),
    ]
